In [1]:
import pandas as pd
import torch
from torch_geometric.transforms import RandomLinkSplit
from sklearn.manifold import TSNE
import plotly.express as px
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)



from train_model_DESC import run_training, LM, lmbda
from train_model_DESC import main

/home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_geometric/typing.py:68: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/libpyg.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_geometric/typing.py:86: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_scatter/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_geometric/typing.py:97: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: /home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_cluster/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-cluster'. "
/home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_geometric/typing.py:113: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: /home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_spline_conv/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(
/home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
/home/giobbi/DDI_LLM_repo/DDI_with_ML/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def get_node_embeddings(model, data):
    model.eval()
    with torch.no_grad():
        node_embeddings = model.encode(data.x, data.edge_index)
    node_embeddings = node_embeddings.cpu().numpy()
    return node_embeddings

def get_reduced_embeddings(node_embeddings):
    # Initialize t-SNE with 2 components for 2D visualization
    tsne = TSNE(n_components=2 ) #, random_state=42) # 42

    # Apply t-SNE to the drug embeddings
    reduced_embeddings = tsne.fit_transform(node_embeddings)

    return pd.DataFrame(reduced_embeddings, columns=['TSNE-1', 'TSNE-2'])

def plot_embeddings(reduced_embeddings_df):
    # Create a scatter plot using Plotly
    fig = px.scatter(
        reduced_embeddings_df,
        x='TSNE-1',
        y='TSNE-2',
        title='t-SNE Visualization of Drug Embeddings',
        width=800,
        height=600
    )
    fig.show()
    #return fig

In [5]:
globals().update(main()) # Pass local variables from main() to the global scope

======== GPT+Desc | LR: 0.0003 ========
-------------------------------
Training with LR: 0.0003
Epoch: 001, Loss: 0.7022, Val: 0.6530
Epoch: 002, Loss: 0.6970, Val: 0.6921
Epoch: 003, Loss: 0.6946, Val: 0.7347
Epoch: 004, Loss: 0.6935, Val: 0.7929
Epoch: 005, Loss: 0.6931, Val: 0.8291
Epoch: 006, Loss: 0.6927, Val: 0.8857
Epoch: 007, Loss: 0.6923, Val: 0.9141
Epoch: 008, Loss: 0.6920, Val: 0.9360
Epoch: 009, Loss: 0.6916, Val: 0.9509
Epoch: 010, Loss: 0.6913, Val: 0.9606
Epoch: 011, Loss: 0.6908, Val: 0.9666
Epoch: 012, Loss: 0.6904, Val: 0.9700
Epoch: 013, Loss: 0.6898, Val: 0.9728
Epoch: 014, Loss: 0.6892, Val: 0.9749
Epoch: 015, Loss: 0.6885, Val: 0.9773
Epoch: 016, Loss: 0.6875, Val: 0.9759
Epoch: 017, Loss: 0.6865, Val: 0.9760
Epoch: 018, Loss: 0.6855, Val: 0.9769
Epoch: 019, Loss: 0.6843, Val: 0.9780
Epoch: 020, Loss: 0.6831, Val: 0.9787
Epoch: 021, Loss: 0.6818, Val: 0.9785
Epoch: 022, Loss: 0.6801, Val: 0.9802
Epoch: 023, Loss: 0.6788, Val: 0.9800
Epoch: 024, Loss: 0.6773, Val: 0.9786
Epoch: 025, Loss: 0.6749, Val: 0.9794
Epoch: 026, Loss: 0.6735, Val: 0.9773
Epoch: 027, Loss: 0.6711, Val: 0.9774
Epoch: 028, Loss: 0.6688, Val: 0.9774
Epoch: 029, Loss: 0.6664, Val: 0.9774
Epoch: 030, Loss: 0.6644, Val: 0.9757
Epoch: 031, Loss: 0.6626, Val: 0.9756
Epoch: 032, Loss: 0.6600, Val: 0.9751
Early stopping at epoch 32
Model: GPT+Desc, LR: 0.0003, Metrics: {'AUC': 0.980611774266249, 'PR_AUC': 0.9793058883668095}

In [3]:
emb[0].shape

(8723, 1536)

In [ ]:
current_graph

           src      dst
0      DB00862  DB00966
1      DB00575  DB00806
2      DB01242  DB08893
3      DB01151  DB08883
4      DB01235  DB01275
...        ...      ...
48509  DB00542  DB01354
48510  DB00476  DB01239
48511  DB00621  DB01120
48512  DB00808  DB01356
48513  DB00677  DB06287

[48514 rows x 2 columns]

In [6]:
drugID_DESC

,Drug ID,Drug Name,Discription,0,1,2,3,4,5,6,...,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535
0,DB00001,Lepirudin,Lepirudin is a recombinant hirudin formed by 6...,-0.023243,-0.003074,-0.012402,-0.001186,-0.000536,0.003723,-0.008107,...,0.013473,-0.018314,0.053811,-0.038109,-0.019970,0.010234,0.000348,-0.016429,-0.003619,0.006386
1,DB00002,Cetuximab,Cetuximab is a recombinant chimeric human/mous...,-0.039815,-0.006620,-0.013445,-0.024023,0.011249,0.006637,-0.027192,...,0.015463,0.010131,0.033266,-0.010604,-0.031268,0.001842,-0.041787,-0.012721,-0.009013,-0.001828
2,DB00003,Dornase alfa,Dornase alfa is a biosynthetic form of human d...,-0.032719,0.000878,-0.014393,-0.015269,-0.009142,0.033176,-0.027683,...,0.036435,-0.007951,0.005945,-0.004393,-0.010314,-0.005931,-0.007217,-0.008685,0.015861,0.005022
3,DB00004,Denileukin diftitox,A recombinant DNA-derived cytotoxic protein co...,-0.042006,-0.000229,-0.053231,-0.014633,0.003604,0.037218,-0.013145,...,0.021611,-0.006350,0.020989,-0.025750,-0.033107,0.009663,-0.009947,-0.026453,-0.004561,-0.006079
4,DB00005,Etanercept,Dimeric fusion protein consisting of the extra...,-0.021316,0.011136,-0.027183,-0.007539,-0.003882,0.007035,-0.031855,...,0.011249,-0.010711,0.043535,-0.009829,-0.010452,0.015994,0.003451,-0.030660,0.017600,-0.029333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8718,DB17378,MVR-T3011,MVR-T3011 is a genetically modified oncolytic ...,-0.023809,0.003932,-0.029748,-0.016298,-0.011464,0.015172,-0.005807,...,0.018060,-0.007329,0.022657,-0.005579,-0.018589,0.005522,-0.004376,-0.028826,-0.003522,-0.002961
8719,DB17379,(-)-Gossypol,"(-)-Gossypol or (R)-Gossypol, is the R-isomer ...",-0.020578,0.002488,-0.006291,-0.020375,-0.027351,0.009479,0.003913,...,0.012475,-0.000130,0.005158,-0.021171,-0.041182,0.025435,0.012050,-0.014101,0.001480,-0.032412
8720,DB17380,Saposin C,"Saposin C is a lysosomal protein. Recombinant,...",-0.014438,0.003586,-0.008844,-0.022089,-0.034169,0.022322,0.003354,...,0.008035,-0.003274,0.032908,0.002837,-0.002831,0.012813,-0.015316,-0.022226,0.013636,-0.002451
8721,DB17381,Nadofaragene firadenovec,Nadofaragene firadenovec (nadofaragene firaden...,-0.020511,-0.014011,-0.025659,-0.002250,-0.001924,0.013731,-0.042987,...,0.025741,0.019828,0.050197,-0.030971,-0.016291,0.027734,0.000253,-0.038508,-0.006019,0.001246
8722,DB17382,AUM-601,AUM-601 is a highly selective pan-TRK(tropomyo...,-0.018780,-0.016442,-0.007953,-0.038500,-0.014901,0.031579,-0.020321,...,0.006047,0.002953,0.031056,0.001469,-0.015071,0.012322,-0.018336,-0.003291,-0.005332,-0.006393

In [4]:
embedding = get_node_embeddings(model, data)
embedding = get_reduced_embeddings(embedding)

In [5]:
plot_embeddings(embedding)

In [30]:
# TODO: add labels to the plot using drugID_DESC -> Make sure the order of embeddings matches the order of drugID_DESC
# TODO: color by drug category if available